# Lista de containers do projeto
services:

  # Container do API Gateway
  gateway:
    # Caminho onde está o Dockerfile do gateway
    build: ../gateway

    # Nome do container
    container_name: api-gateway

    # Porta do computador : porta do container
    ports:
      - "5000:5000"

    # Gateway depende dos outros serviços
    depends_on:
      - auth-service
      - task-service
      - notification-service

  # Container do serviço de autenticação
  auth-service:
    # Caminho onde está o Dockerfile do auth-service
    build: ../services/auth-service

    # Nome do container
    container_name: auth-service

    # Porta 5001
    ports:
      - "5001:5001"

  # Container do serviço de tarefas
  task-service:
    # Caminho onde está o Dockerfile do task-service
    build: ../services/task-service

    # Nome do container
    container_name: task-service

    # Porta 5002
    ports:
      - "5002:5002"

  # Container do serviço de notificações
  notification-service:
    # Caminho onde está o Dockerfile do notification-service
    build: ../services/notification-service

    # Nome do container
    container_name: notification-service

    # Porta 5003
    ports:
      - "5003:5003"
```
