services:
  gateway:
    build: ../gateway
    container_name: api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - task-service
      - notification-service

  auth-service:
    build: ../services/auth-service
    container_name: auth-service
    ports:
      - "5001:5001"

  task-service:
    build: ../services/task-service
    container_name: task-service
    ports:
      - "5002:5002"

  notification-service:
    build: ../services/notification-service
    container_name: notification-service
    ports:
      - "5003:5003"