name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Verificar GCC
        run: gcc --version

      - name: Compilar auth-service
        run: gcc services/auth-service/main.c -o /tmp/auth-service

      - name: Compilar task-service
        run: gcc services/task-service/main.c -o /tmp/task-service

      - name: Compilar notification-service
        run: gcc services/notification-service/main.c -o /tmp/notification-service

      - name: Compilar gateway
        run: gcc gateway/main.c -o /tmp/gateway